openapi: 3.0.0
info:
  title: Hi-Lo Game
  description: |
    This API allow playing hi-lo game
    and requesting the state of a game or the history
    of all games
  version: 0.0.1
paths:
  /games:
    post:
      summary: Start a new game
      description: | 
        Start a new game generating the secret number
        and return the created game ID.
      responses:
        "200":
          description: New game created
          content:
            application/json:
              schema:
                type: integer
        "500":
          description: Internal server error

    get:
      summary: Get all games
      description: |
        Get the collection of all game IDs and their status.
      responses:
        "200":
          description: List of all games
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/Game"
        "404":
          description: Games not found
        "500":
          description: Internal server error

  /games/{id}:
    get:
      summary: Get the list of all guesses from a game
      description: |
        Based on the game ID, returns a list of guesses from a game and their responses.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the game.
          schema:
            type: integer
      responses:
        "200":
          description: List of all guesses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Guess"
        "400":
          description: Invalid input
        "404":
          description: Game not found
        "500":
          description: Internal server error
    put:
      summary: Reset a game
      description: Reset a game by its ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the game.
          schema:
            type: integer
      responses:
        "200":
          description: Game reset successful.
        "400":
          description: Invalid input.
        "404":
          description: Game not found.
        "500":
          description: Internal server error.
    post:
      summary: Submit a guess.
      description: Submit a guess
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the task.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: integer
      responses:
        "200":
          description: Guess submitted sucessfully.
          content:
           application/json:
             schema:
               type: string
        "400":
          description: Invalid input.
        "404":
          description: Game not found.
        "500":
          description: Internal server error.
    
components:
  schemas:
    Guess:
      type: object
      properties:
        guessed_number:
          type: integer
        response:
          type: string
        
    Game:
      type: object
      properties:
        id:
          type: integer
        status:
          type: string
        secret:
          type: integer
        guesses:
          type: array
          items: 
            $ref: '#/components/schemas/Guess'
  
        
